name: Geode

on: [push, pull_request]

env:
  # Your Geode Mod Id
  GEODE_MOD_ID: gay.rooot.gdmp

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            os_identifier: win

          - os: macos-latest
            os_identifier: mac

    runs-on: ${{ matrix.config.os }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download Geode CLI
        uses: robinraju/release-downloader@v1.5
        with:
          repository: geode-sdk/cli
          latest: true
          fileName: "*-${{matrix.config.os_identifier}}.zip"
          tarBall: false
          zipBall: false
          out-file-path: "../cli"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Geode CLI
        run: |
          cd ../
          7z x "cli/*-${{ matrix.config.os_identifier }}.zip" -o"${{github.workspace}}/../cli"
          echo "${{ github.workspace }}/../cli" >> $GITHUB_PATH

      - name: Make Geode CLI executable
        if: runner.os == 'macOS'
        run: chmod +x ../cli/geode

      - name: Geode SDK
        if: runner.os == 'macOS'
        run: |
          geode sdk install --force /Users/Shared/Geode/sdk

      - name: Geode SDK
        if: runner.os == 'Windows'
        run: |
            ../cli/geode sdk install --force C:\Users\runneradmin\Documents\Geode

      - name: Configure Geode
        run: |
          geode config setup
          geode profile add -n Default "${{github.workspace}}/../dummy"
          geode profile switch Default

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Zipping
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.os_identifier}}
          path: build/${{env.GEODE_MOD_ID}}.geode
