name: Geode

on: [push, pull_request]

env:
  # Your Geode Mod Id
  GEODE_MOD_ID: gay.rooot.gdmp

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: windows-latest
            os_identifier: win

          - os: macos-latest
            os_identifier: mac

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download Geode CLI
        uses: robinraju/release-downloader@v1
        with:
          repository: geode-sdk/cli
          tag: "v2.4.0"
          fileName: "*-${{matrix.config.os_identifier}}.zip"
          tarBall: false
          zipBall: false
          out-file-path: "../cli"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Geode CLI
        run: |
          cd ../cli
          ls -a
          7z x "cli/*-${{ matrix.config.os_identifier }}.zip" -o cli
          echo "$PWD/cli" >> $GITHUB_PATH

      - name: Geode SDK
        run: |
          geode sdk install

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Zipping
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.os_identifier}}
          path: build/${{env.GEODE_MOD_ID}}.geode
