name: Build Geode mod

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  CLI_VERSION: v2.4.3
  GEODE_VERSION: v1.0.3

jobs:
  build:
    strategy:
      matrix:
        config:
        - name: Windows
          os: windows-latest
          
        - name: macOS
          os: macos-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          sdk: ${{ env.GEODE_SDK }}
          cli: ${{ env.CLI_VERSION }}
      
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod@combine
        id: build

      - uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
