name: Geode

on: [push, pull_request]

env:
  # Your Geode Mod Id
  GEODE_MOD_ID: gay.rooot.gdmp

jobs:
  build:
    strategy:
      matrix:
        config:
          #         os: [macos-latest, windows-latest]
          # os: [macos-latest]
          - name: windows-latest
            os_identifier: win

          - os: macos-latest
            os_identifier: mac

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download CLI
        uses: robinraju/release-downloader@v1
        with:
          repository: geode-sdk/cli
          latest: true
          fileName: "*-${{ matrix.config.os_identifier }}.zip"
          tarBall: false
          zipBall: false
          out-file-path: "cli"

      - name: Unzip CLI
        run: |
          7z x "${{ github.workspace }}/cli/*-${{ matrix.config.os_identifier }}.zip" -o"${{ github.workspace }}/cli"

      - name: Add CLI to Path
        run: |
          echo "${{ github.workspace }}/cli" >> $GITHUB_PATH

      - name: Geode SDK
        run: |
          geode sdk install

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Zipping
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.os_identifier}}
          path: build/${{env.GEODE_MOD_ID}}.geode
