name: Build Geode mod

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  CLI_VERSION: v2.4.4
  GEODE_VERSION: nightly
  PREBUILT_PROTOBUF_VERSION: v21.12

jobs:
  build:
    strategy:
      matrix:
        config:
        - name: Windows
          os: windows-latest
          
        - name: macOS
          os: macos-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: 'prebuilt-protobuf'
          path: "prebuilt_protobuf"

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: 'protocolbuffers/protobuf'
          ref: ${{ env.PREBUILT_PROTOBUF_VERSION }}
          path: "prebuilt_protobuf/src"

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          configure-args: '-DUSE_PREBUILT_PROTOBUF=1 -DGEODE_DISABLE_CLI_CALLS=1'
          build-args: '-j 16'
          sdk: ${{ env.GEODE_SDK }}
          cli: ${{ env.CLI_VERSION }}
          combine: true
      
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod@combine
        id: build

      - uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
